name       : gaupol
version    : '1.8'
release    : 14
source     :
    - https://github.com/otsaloma/gaupol/archive/1.8.tar.gz : 14584337d20e7b15a3bca719cb919b7c12cd0a13b21e8ae9df5a562c54f1cdc9
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : Editor for text-based subtitle files.
description: |
    Gaupol is an editor for text-based subtitle files. It supports multiple subtitle file formats and provides means of creating, editing and translating subtitles and timing subtitles to match video.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - gspell
    - iso-codes
    - python-chardet
    - python-gobject
build      : |
    %python3_setup
install    : |
    %python3_install
