name       : gaupol
version    : '1.11'
release    : 18
source     :
    - https://github.com/otsaloma/gaupol/archive/refs/tags/1.11.tar.gz : ae9ca544c27dd0d94162d78f92f98e5c51c69141c952eeea270c6a063374510d
license    : GPL-3.0-or-later
homepage   : https://otsaloma.io/gaupol/
component  : multimedia.video
summary    : Editor for text-based subtitle files.
description: |
    Gaupol is an editor for text-based subtitle files. It supports multiple subtitle file formats and provides means of creating, editing and translating subtitles and timing subtitles to match video.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - gspell
    - iso-codes
    - python-chardet
    - python-gobject
build      : |
    %python3_setup
install    : |
    %python3_install
