name       : gaupol
version    : '1.7'
release    : 11
source     :
    - https://github.com/otsaloma/gaupol/archive/1.7.tar.gz : 250b0d929e635eec89656dc9672f5dba3bc0324325008f17155b3e54ac560788
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : Editor for text-based subtitle files.
description: |
    Gaupol is an editor for text-based subtitle files. It supports multiple subtitle file formats and provides means of creating, editing and translating subtitles and timing subtitles to match video.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - gspell
    - iso-codes
    - python-chardet
    - python3-gobject
build      : |
    %python3_setup
install    : |
    %python3_install
